name=input("enter your name:")
print(name)
age=input("enter your age:")
print(age)
favcolor=input("enter your favourite color:")
print(favcolor)
zodiac=input("enter your zodiac sign:")
print(zodiac)